### ISSUE TITLE
primitive聚合

### ISSUE THREAD

**Issue by zhoudong666** [tingyuxuan2302/cesium-vue3-vite#4]
请问, 如果通过 primitivecluster 添加的点位聚合, 怎么动态的移除, 在次添加, 比如A公司1万人, B公司1万人, C公司1万人, 选择 ABC三个公司就是三万个点位, 切换只选择A公司, 就只有1万人

**Comment by tingyuxuan2302** [comment]
> 请问, 如果通过 primitivecluster 添加的点位聚合, 怎么动态的移除, 在次添加, 比如A公司1万人, B公司1万人, C公司1万人, 选择 ABC三个公司就是三万个点位, 切换只选择A公司, 就只有1万人

 primitives.removeAll()
