### ISSUE TITLE
请问 我想点击第一批数据的primitive 加载另外一组数据的点 并且销毁第一批的要怎么做呢

### ISSUE THREAD

**Issue by srarlight** [tingyuxuan2302/cesium-vue3-vite#6]
初学cesium 遇到了这个问题，尝试了很久 一直报错，百思不得其解。
![image](https://github.com/tingyuxuan2302/cesium-vue3-vite/assets/46178001/a3b7e9b8-03fd-4fd4-acff-518be28ba234)

**Comment by tingyuxuan2302** [comment]
先执行primitives.removeAll()，然后primitive还有一个isDestroyed属性，这个属性是可判断是否已经销毁primitive

**Comment by srarlight** [comment]
重新执行formatClusterPoint 方法就会报这个错。不懂这是啥原因~

starlight
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tingyuxuan2302/cesium-vue3-vite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 上午9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tingyuxuan2302/cesium-vue3-vite] 请问 我想点击第一批数据的primitive 加载另外一组数据的点 并且销毁第一批的要怎么做呢 (Issue #6)





 
先执行primitives.removeAll()，然后primitive还有一个isDestroyed属性，这个属性是可判断是否已经销毁primitive

**Comment by srarlight** [comment]
PrimitiveCluster 这个方法 在cesium 源码中没有找到~初步怀疑是primitive.removeAll 方法有问题呢，大佬可以尝试下 你的项目清除打点后 也不能重新primitive打点了




starlight
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tingyuxuan2302/cesium-vue3-vite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 上午9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tingyuxuan2302/cesium-vue3-vite] 请问 我想点击第一批数据的primitive 加载另外一组数据的点 并且销毁第一批的要怎么做呢 (Issue #6)





 
先执行primitives.removeAll()，然后primitive还有一个isDestroyed属性，这个属性是可判断是否已经销毁primitive

**Comment by tingyuxuan2302** [comment]
该问题已修复，执行formatClusterPoint的时候需要重新new Cesium.BillboardCollection()和new Cesium.PrimitiveCollection()，因为cesium告知销毁后的实例无法再次使用

**Comment by liyuzhuang007** [comment]
An error occurred while rendering.  Rendering has stopped.
DeveloperError: Width must be less than or equal to the maximum texture size (0).  Check maximumTextureSize.

请问相机视角改变事件报这个错是什么原因
