### ISSUE TITLE
相机视角改变事件报错

### ISSUE THREAD

**Issue by liyuzhuang007** [tingyuxuan2302/cesium-vue3-vite#7]
Cesium.js:12496 An error occurred while rendering.  Rendering has stopped.
DeveloperError: Width must be less than or equal to the maximum texture size (0).  Check maximumTextureSize.

请问这个是什么原因

**Comment by tingyuxuan2302** [comment]
> Cesium.js:12496 An error occurred while rendering. Rendering has stopped. DeveloperError: Width must be less than or equal to the maximum texture size (0). Check maximumTextureSize.
> 
> 请问这个是什么原因

看报错原因，应该是你设置的相机视角参数，如width超出了材质的大小导致的报错，把视角参数改小一点试试
